# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Detecting-outliers" data-toc-modified-id="Detecting-outliers-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Detecting outliers</a></div><div class="lev2 toc-item"><a href="#A-function-to-detect-outliers" data-toc-modified-id="A-function-to-detect-outliers-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>A function to detect outliers</a></div><div class="lev1 toc-item"><a href="#Generate-some-random-data" data-toc-modified-id="Generate-some-random-data-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Generate some random data</a></div><div class="lev1 toc-item"><a href="#Outliers-in-the-normal-distribution" data-toc-modified-id="Outliers-in-the-normal-distribution-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Outliers in the normal distribution</a></div><div class="lev2 toc-item"><a href="#Outliers-from-the-boxplot-generator" data-toc-modified-id="Outliers-from-the-boxplot-generator-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Outliers from the boxplot generator</a></div><div class="lev2 toc-item"><a href="#Outliers-with-threshold=3.5" data-toc-modified-id="Outliers-with-threshold=3.5-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Outliers with threshold=3.5</a></div><div class="lev2 toc-item"><a href="#What-threshold-value-do-we-need?" data-toc-modified-id="What-threshold-value-do-we-need?-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>What threshold value do we need?</a></div><div class="lev1 toc-item"><a href="#Outliers-in-the-LogNormal-distribution" data-toc-modified-id="Outliers-in-the-LogNormal-distribution-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Outliers in the LogNormal distribution</a></div><div class="lev2 toc-item"><a href="#from-the-boxplot-generator" data-toc-modified-id="from-the-boxplot-generator-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>from the boxplot generator</a></div><div class="lev2 toc-item"><a href="#with-the-default-threshold,-3.5" data-toc-modified-id="with-the-default-threshold,-3.5-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>with the default threshold, <code>3.5</code></a></div><div class="lev2 toc-item"><a href="#Finding-the-threshold" data-toc-modified-id="Finding-the-threshold-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Finding the threshold</a></div><div class="lev2 toc-item"><a href="#Building-a-loop-to-find-outliers-and-threshold" data-toc-modified-id="Building-a-loop-to-find-outliers-and-threshold-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Building a loop to find outliers and threshold</a></div><div class="lev1 toc-item"><a href="#A-function-to-find-a-certain-number-of-outliers" data-toc-modified-id="A-function-to-find-a-certain-number-of-outliers-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>A function to find a certain number of outliers</a></div><div class="lev2 toc-item"><a href="#Write-the-function" data-toc-modified-id="Write-the-function-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Write the function</a></div><div class="lev2 toc-item"><a href="#Test-the-function-for-LogNormal" data-toc-modified-id="Test-the-function-for-LogNormal-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Test the function for LogNormal</a></div><div class="lev2 toc-item"><a href="#Test-the-function-for-Exponential" data-toc-modified-id="Test-the-function-for-Exponential-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Test the function for Exponential</a></div><div class="lev3 toc-item"><a href="#Outliers-from-1.5-IQR" data-toc-modified-id="Outliers-from-1.5-IQR-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>Outliers from <code>1.5 IQR</code></a></div><div class="lev3 toc-item"><a href="#Using-z-score-with-a-threshold-of-3.5" data-toc-modified-id="Using-z-score-with-a-threshold-of-3.5-5.3.2"><span class="toc-item-num">5.3.2&nbsp;&nbsp;</span>Using z-score with a threshold of 3.5</a></div><div class="lev3 toc-item"><a href="#Find-the-same-outliers-as-boxplot" data-toc-modified-id="Find-the-same-outliers-as-boxplot-5.3.3"><span class="toc-item-num">5.3.3&nbsp;&nbsp;</span>Find the same outliers as boxplot</a></div><div class="lev1 toc-item"><a href="#Conclusions" data-toc-modified-id="Conclusions-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Conclusions</a></div>

# Detecting outliers

## A function to detect outliers

http://stackoverflow.com/questions/22354094/pythonic-way-of-detecting-outliers-in-one-dimensional-observation-data

In [3]:
def is_outlier(points, thresh=3.5):
    """
    Returns a boolean array with True if points are outliers and False 
    otherwise.

    Parameters:
    -----------
        points : An numobservations by numdimensions array of observations
        thresh : The modified z-score to use as a threshold. Observations with
            a modified z-score (based on the median absolute deviation) greater
            than this value will be classified as outliers.

    Returns:
    --------
        mask : A numobservations-length boolean array.

    References:
    ----------
        Boris Iglewicz and David Hoaglin (1993), "Volume 16: How to Detect and
        Handle Outliers", The ASQC Basic References in Quality Control:
        Statistical Techniques, Edward F. Mykytka, Ph.D., Editor. 
    """
    if len(points.shape) == 1:
        points = points[:,None]
    median = np.median(points, axis=0)
    diff = np.sum((points - median)**2, axis=-1)
    diff = np.sqrt(diff)
    med_abs_deviation = np.median(diff)

    modified_z_score = 0.6745 * diff / med_abs_deviation

    return modified_z_score > thresh

# Generate some random data

In [95]:
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon


# Generate some data from five different probability distributions,
# each with different characteristics. We want to play with how an IID
# bootstrap resample of the data preserves the distributional
# properties of the original sample, and a boxplot is one visual tool
# to make this assessment
numDists = 5
randomDists = ['Normal(1,1)', ' Lognormal(1,1)', 'Exp(1)', 'Gumbel(6,4)',
               'Triangular(2,9,11)']
N = 500

np.random.seed(250)

norm = np.random.normal(1, 1, N)
logn = np.random.lognormal(1, 1, N)
expo = np.random.exponential(1, N)
gumb = np.random.gumbel(6, 4, N)
tria = np.random.triangular(2, 9, 11, N)

# Generate some random indices that we'll use to resample the original data
# arrays. For code brevity, just use the same random indices for each array
# bootstrapIndices = np.random.random_integers(0, N - 1, N)
bootstrapIndices = np.random.randint(0, N-1, N)

normBoot = norm[bootstrapIndices]
expoBoot = expo[bootstrapIndices]
gumbBoot = gumb[bootstrapIndices]
lognBoot = logn[bootstrapIndices]
triaBoot = tria[bootstrapIndices]

data = [norm, normBoot, logn, lognBoot, expo, expoBoot, gumb, gumbBoot,
        tria, triaBoot]

# Outliers in the normal distribution

## Outliers from the boxplot generator
This generates outliers as per default value in boxplot, `whis=1.5`.

This is the outliers data from boxplot:

## Outliers with threshold=3.5

In [99]:
norm = data[0]

Data extracted with the default threshold=3.5

In [100]:
mask = is_outlier(norm)    #: boolean array with outliers
norm[mask]

array([], dtype=float64)

__How many outliers?__

> None!

## What threshold value do we need?

In [103]:
mask = is_outlier(norm, 3)    #: boolean array with outliers
norm[mask]

array([-2.0231389 ,  3.99741747])

> Too few!

In [104]:
mask = is_outlier(norm, 2)    #: boolean array with outliers
norm[mask]

array([-1.44563201, -1.28389833,  3.08484642, -1.40075503, -1.4241279 ,
       -1.53645618, -1.71621774,  2.92521876, -2.0231389 ,  3.16262969,
        3.61505755,  3.18380039,  3.99741747,  2.98251006,  3.53384002,
       -1.12572378,  2.96502457,  3.0946063 , -1.15366383,  3.65833982,
        3.15641456,  2.97643175,  2.98182184, -1.19618263,  3.09011863,
       -1.36191208, -1.08362714,  3.09716204,  3.87308106, -1.30504305,
       -1.01643675, -1.3867649 ])

> Too many!

Data being pulled out from the distribution with `threshold=2.725`.

In [101]:
mask = is_outlier(norm, 2.725)    #: boolean array with outliers
norm[mask]

array([-1.71621774, -2.0231389 ,  3.99741747,  3.65833982,  3.87308106])

> We can see that by using `threshold=3.5` the outliers in the normal distribution are _none_, while with `2.725` yields the exact same number of outliers generated by boxplot with `whis=1.5`, which is the same as saying `1.5 * IQR`

> This tells us that boxplot is very liberal at the moment of generating outliers.



# Outliers in the LogNormal distribution

## from the boxplot generator

We obtained `45` values when the default values of `whis=1.5` is used.

This is the data.

In [106]:
logn_out = np.array([ 13.34965575,  11.20386923,  26.77229609,  16.23283858,
         15.14414748,  13.52070055,  13.29336908,  14.80216194,
         14.07009024,  11.0530542 ,  32.57269232,  26.70876076,
         12.25599026,  13.77100335,  12.76185192,  15.53305149,
         17.72415461,  10.71883218,  11.64097131,  12.72226004,
         10.75128195,  13.78857614,  10.83787431,  16.96749617,
         13.77689348,  15.79019831,  26.9281414 ,  18.15055167,
         18.7588332 ,  14.518236  ,  13.56524146,  11.01765864,
         11.14188114,  14.93714977,  14.9757271 ,  10.63014604,
         19.36354811,  17.42765612,  26.12290182,  14.68222579,
         12.90920417,  22.85929865,  19.64187528,  24.23580033,  13.80488068])


print(len(logn_out))
print(np.sort(logn_out))

45
[ 10.63014604  10.71883218  10.75128195  10.83787431  11.01765864
  11.0530542   11.14188114  11.20386923  11.64097131  12.25599026
  12.72226004  12.76185192  12.90920417  13.29336908  13.34965575
  13.52070055  13.56524146  13.77100335  13.77689348  13.78857614
  13.80488068  14.07009024  14.518236    14.68222579  14.80216194
  14.93714977  14.9757271   15.14414748  15.53305149  15.79019831
  16.23283858  16.96749617  17.42765612  17.72415461  18.15055167
  18.7588332   19.36354811  19.64187528  22.85929865  24.23580033
  26.12290182  26.70876076  26.77229609  26.9281414   32.57269232]


## with the default threshold, `3.5`

Using the function is_outlier() with the default value of `threshold=1.5`.

In [107]:
mask = is_outlier(data[2])    #: boolean array with outliers
print(len(data[2][mask]))
data[2][mask]

39


array([ 13.34965575,  11.20386923,  26.77229609,  16.23283858,
        15.14414748,  13.52070055,  13.29336908,  14.80216194,
        14.07009024,  32.57269232,  26.70876076,  12.25599026,
        13.77100335,  12.76185192,  15.53305149,  17.72415461,
        11.64097131,  12.72226004,  13.78857614,  16.96749617,
        13.77689348,  15.79019831,  26.9281414 ,  18.15055167,
        18.7588332 ,  14.518236  ,  13.56524146,  11.14188114,
        14.93714977,  14.9757271 ,  19.36354811,  17.42765612,
        26.12290182,  14.68222579,  12.90920417,  22.85929865,
        19.64187528,  24.23580033,  13.80488068])

> We get only 39 values, which means that the function is being very conservative.

## Finding the threshold

From above, we see that by using `threshold=3.5` we get only 39 outliers.

In [58]:
mask = is_outlier(data[2], 3.5)    #: boolean array with outliers
print(len(data[2][mask]))
print(np.sort(data[2][mask]))

39
[ 11.14188114  11.20386923  11.64097131  12.25599026  12.72226004
  12.76185192  12.90920417  13.29336908  13.34965575  13.52070055
  13.56524146  13.77100335  13.77689348  13.78857614  13.80488068
  14.07009024  14.518236    14.68222579  14.80216194  14.93714977
  14.9757271   15.14414748  15.53305149  15.79019831  16.23283858
  16.96749617  17.42765612  17.72415461  18.15055167  18.7588332
  19.36354811  19.64187528  22.85929865  24.23580033  26.12290182
  26.70876076  26.77229609  26.9281414   32.57269232]


What threshold value do we need to get 45 outliers?

## Building a loop to find outliers and threshold

In [78]:
thr = 3.500
eps = 0.001
while True:
    mask = is_outlier(data[2], thr)    #: boolean array with outliers
    count = len(data[2][mask])
    # print(count)
    thr = thr - eps
    if count == 45:
        break
print(count, thr)      
print(np.sort(data[2][mask]))

45 3.311
[ 10.63014604  10.71883218  10.75128195  10.83787431  11.01765864
  11.0530542   11.14188114  11.20386923  11.64097131  12.25599026
  12.72226004  12.76185192  12.90920417  13.29336908  13.34965575
  13.52070055  13.56524146  13.77100335  13.77689348  13.78857614
  13.80488068  14.07009024  14.518236    14.68222579  14.80216194
  14.93714977  14.9757271   15.14414748  15.53305149  15.79019831
  16.23283858  16.96749617  17.42765612  17.72415461  18.15055167
  18.7588332   19.36354811  19.64187528  22.85929865  24.23580033
  26.12290182  26.70876076  26.77229609  26.9281414   32.57269232]


> We obtained __45 outliers__ with a threhold value of __3.311__.

# A function to find a certain number of outliers

## Write the function
Based on the loop above we rewrite the code as:

In [108]:
def find_n_outliers(data, n, threshold=3.5, eps=0.001):
    while True:
        mask = is_outlier(data, threshold)    #: boolean array with outliers
        count = len(data[mask])
        # print(count)
        threshold = threshold - eps
        if count == n:
            break
    print(count, threshold)      
    print(np.sort(data[mask]))

## Test the function for LogNormal

In [109]:
find_n_outliers(data[2], 45)

45 3.311
[ 10.63014604  10.71883218  10.75128195  10.83787431  11.01765864
  11.0530542   11.14188114  11.20386923  11.64097131  12.25599026
  12.72226004  12.76185192  12.90920417  13.29336908  13.34965575
  13.52070055  13.56524146  13.77100335  13.77689348  13.78857614
  13.80488068  14.07009024  14.518236    14.68222579  14.80216194
  14.93714977  14.9757271   15.14414748  15.53305149  15.79019831
  16.23283858  16.96749617  17.42765612  17.72415461  18.15055167
  18.7588332   19.36354811  19.64187528  22.85929865  24.23580033
  26.12290182  26.70876076  26.77229609  26.9281414   32.57269232]


## Test the function for Exponential

### Outliers from `1.5 IQR`

In [91]:
expo = np.array([ 4.6984617 ,  4.1090784 ,  4.3521881 ,  3.76239879,  3.35289481,
         3.52379525,  3.75823679,  3.73336056,  3.91320399,  3.52185724,
         4.46332529,  4.83949345,  3.43924036,  4.61837801,  3.53029566,
         3.40557258,  4.25470651,  3.62684076])

print(np.sort(expo))
len(expo)

[ 3.35289481  3.40557258  3.43924036  3.52185724  3.52379525  3.53029566
  3.62684076  3.73336056  3.75823679  3.76239879  3.91320399  4.1090784
  4.25470651  4.3521881   4.46332529  4.61837801  4.6984617   4.83949345]


18

> 18 outliers

### Using z-score with a threshold of 3.5

In [92]:
mask = is_outlier(expo)    #: boolean array with outliers
print(len(expo[mask]))
expo[mask]

0


array([], dtype=float64)

> We get zero outliers. Too conservative!

### Find the same outliers as boxplot

In [93]:
find_n_outliers(expo, 18)

18 0.00300000000027
[ 3.35289481  3.40557258  3.43924036  3.52185724  3.52379525  3.53029566
  3.62684076  3.73336056  3.75823679  3.76239879  3.91320399  4.1090784
  4.25470651  4.3521881   4.46332529  4.61837801  4.6984617   4.83949345]


> Now, we get the same outliers as in boxplot.

> Notice how small the __threshold__ had to be to produce the same number of outliers as `1.5*IQR`.

# Conclusions

1. A threshold of 3.5 in the z-score Iglewicz-Hoaglin algorithm seems to be __too conservative__ or too high limiting the number of outliers.

2. This may cause to include values that are __too extreme__.

3. The `threshold` parameter is __not linear__.

4. The `threshold` value has __no the same effect on all distributions__; in some a small change in the `threshold` will produce a big production of outliers meanwhile in others the `threshold` will may need to probably go as low as __zero__.

5. In those cases, if could be a better option chosing `1.5` times the `IQR`. Will that yield better data?

6. In the figure below, we can see why the threshold value needs to be so small to give us the same number of outliers as `1.5*IQR`; the outliers are pretty compressed meanwhile in the _LogNormal_ distribution the outliers are more spread out.

[](./images/two_distributions_threshold.png)

![](./images/two_distributions_threshold.png)

> In the next notebook we will explain how we come about the threshold value of `3.5`.